.TH gprayer 1 2006-12-24 Gprayer "Gprayer"
.SH NAME
Gprayer - Gnome Prayer Times
.SH SYNOPSIS
.Begprayer [OPTIONS]
.SH DESCRIPTION
.I gprayer
gprayer is a Gnome Islamic prayer times applications. At first start, you have to configure it with your location, time zone and madhab details. 
\.
.SH OPTIONS
options are directly fed to gtk, gconf and gstreamer initilisations.
.SH AUTHORS
- Djihed Afifi (djihed@gmail.com) - http://djihed.com
