.TH minbar 1 2006-12-24 minbar "minbar"
.SH NAME
Minbar - Gnome Prayer Times
.SH SYNOPSIS
.Beminbar [OPTIONS]
.SH DESCRIPTION
.I minbar
is a Gnome Islamic prayer times application. At first start, you have to configure it with your location, time zone and madhab details. 
\.
.SH OPTIONS
options are directly fed to gtk, gconf and gstreamer initialisations.
.SH AUTHORS
- Djihed Afifi (djihed@gmail.com) - http://djihed.com
